F13 & J::Send,{Blind}{Left}         ;←
F13 & K::Send,{Blind}{Down}         ;↓
F13 & I::Send,{Blind}{Up}           ;↑
F13 & L::Send,{Blind}{Right}        ;→
F13 & U::Send,{Blind}{PgUp}         ;PgUp
F13 & O::Send,{Blind}{PgDn}         ;PgDn
F13 & H::Send,{Blind}{Home}         ;Home
F13 & `;::Send,{Blind}{End}         ;End
F13 & A::Send,{Blind}{Backspace}    ;Backspace
F13 & S::Send,{Blind}{Delete}       ;Delete
F13 & Enter::Send,{Blind}{AppsKey}  ;右クリックメニュー表示
F13 & E::Send,{Blind}{esc}          ;esc